import { PublicMarketNav } from "@/components/PublicMarketNav";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowRight, CheckCircle2, Clock3, FlaskConical, ShieldCheck, XCircle } from "lucide-react";
import React from "react";

function percent(value: number | string | null | undefined) {
  const number = Number(value ?? 0);
  return `${number >= 0 ? "+" : ""}${number.toFixed(2)}%`;
}

function formula(value: unknown) {
  const root = value as { logic?: string; children?: unknown[] } | null;
  return root ? `${root.logic ?? "AND"} · 규칙 ${root.children?.length ?? 0}개` : "조건식 정보 없음";
}

function Stat({ label, value, description, icon: Icon, tone = "teal" }: { label: string; value: string; description: string; icon: typeof Activity; tone?: "teal" | "violet" | "rose" | "amber" }) {
  const palette = { teal: "border-teal-300/20 bg-teal-300/[0.055] text-teal-200", violet: "border-violet-300/20 bg-violet-300/[0.055] text-violet-200", rose: "border-rose-300/20 bg-rose-300/[0.055] text-rose-200", amber: "border-amber-300/20 bg-amber-300/[0.055] text-amber-200" }[tone];
  return <article className={`rounded-2xl border p-5 ${palette}`}><div className="flex items-start justify-between gap-3"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">{label}</p><Icon size={17}/></div><p className="mt-5 font-mono text-3xl font-semibold tracking-tight text-white">{value}</p><p className="mt-2 text-xs leading-relaxed text-slate-500">{description}</p></article>;
}

export default function PublicMinuteResearchDashboard() {
  const dashboard = trpc.minuteResearch.publicDashboard.useQuery(undefined, { retry: false, refetchInterval: 60_000 });
  const latest = dashboard.data?.sweeps[0];
  const coverage = dashboard.data?.dataCoverage;
  const cumulative = dashboard.data?.cumulative ?? [];
  const summary = latest?.summaryJson as { trainingDates?: string[]; validationDates?: string[]; symbolCount?: number } | null;
  const nextAction = coverage?.tradingDateCount ? { href: "/", label: "게임 진입에서 배틀 준비" } : { href: "/datasets", label: "원본 준비로 이동" };
  return <main data-ui-version="minute-research-public-v1" className="min-h-screen bg-[#090e16] px-4 py-6 text-slate-100 sm:px-7 lg:px-10"><PublicMarketNav active="research"/><div className="mx-auto max-w-7xl">
    <header className="relative mt-6 overflow-hidden rounded-3xl border border-teal-300/20 bg-[radial-gradient(circle_at_83%_8%,rgba(45,212,191,0.16),transparent_30%),linear-gradient(135deg,rgba(14,25,37,0.98),rgba(7,13,21,0.98))] p-6 md:p-9"><div className="absolute -right-16 top-0 h-64 w-64 rounded-full border border-teal-300/10"/><div className="relative grid gap-7 lg:grid-cols-[1.35fr_0.65fr] lg:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-teal-300">AUREUM · MINUTE-BAR RESEARCH</p><h1 className="mt-3 max-w-3xl text-4xl font-extrabold tracking-tight text-white md:text-5xl">수천 개 조합을 검증하고,<br/><span className="text-teal-300">누적으로 살아남은 조건식</span>만 남깁니다.</h1><p className="mt-4 max-w-3xl text-base leading-relaxed text-slate-300">실제 저장 1분봉으로 매수·매도 타점과 비용을 반복 검증합니다. 표본 부족·음수 기대값·과도한 낙폭 조합은 기록은 남기되 생존 목록에서는 제외합니다.</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full border border-teal-300/20 bg-teal-300/10 px-3 py-1.5 text-xs font-semibold text-teal-100">연구 전용 · 주문 전송 분리</span><span className="rounded-full border border-violet-300/20 bg-violet-300/10 px-3 py-1.5 text-xs font-semibold text-violet-100">학습/독립 검증 분리</span><span className="rounded-full border border-slate-700 bg-slate-950/40 px-3 py-1.5 text-xs font-semibold text-slate-300">다음 1분 시가 진입 가정</span></div></div><div className="rounded-2xl border border-slate-700 bg-slate-950/40 p-5"><div className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${dashboard.data?.program?.status === "active" ? "bg-teal-300 shadow-[0_0_16px_rgba(45,212,191,0.9)]" : "bg-amber-300"}`}/><p className="text-sm font-bold text-slate-100">{dashboard.data?.program?.status === "active" ? "일별 검증 프로그램 활성" : "연구 프로그램 준비 중"}</p></div><p className="mt-2 text-sm leading-relaxed text-slate-400">{dashboard.data?.program ? `${dashboard.data.program.name} · ${dashboard.data.program.cronExpression}` : "원본 1분봉과 프로그램 설정이 준비되면 검증 이력이 표시됩니다."}</p><a href="/connection-audit" className="mt-5 flex w-full items-center justify-center rounded-xl border border-sky-300/35 bg-sky-300/10 px-4 py-3 text-sm font-bold text-sky-50 transition hover:bg-sky-300/15 active:scale-[0.97]">실행 증거 감사 보기 <ArrowRight className="ml-2" size={16}/></a><a href={nextAction.href} className="mt-2 flex w-full items-center justify-center rounded-xl bg-teal-300 px-4 py-3 text-sm font-bold text-slate-950 transition hover:bg-teal-200 active:scale-[0.97]">{nextAction.label} <ArrowRight className="ml-2" size={16}/></a></div></div></header>

    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="1분봉 원본" value={coverage ? `${coverage.tradingDateCount}일` : "0일"} description={coverage ? `${coverage.firstDate} ~ ${coverage.lastDate} 저장 데이터` : "원본을 기다리고 있습니다."} icon={Activity}/><Stat label="최근 조합 평가" value={latest ? latest.generatedCount.toLocaleString() : "—"} description="중복 없는 조건식 파라미터 조합" tone="violet" icon={FlaskConical}/><Stat label="엄격 통과" value={latest ? `${latest.promotedCount}개` : "—"} description="독립 검증·표본·낙폭 기준 동시 통과" icon={CheckCircle2}/><Stat label="제외·보류" value={latest ? `${latest.rejectedCount.toLocaleString()}개` : "—"} description="음수·낙폭·표본 부족은 생존 목록 제외" tone="rose" icon={XCircle}/></section>

    <section className="mt-6 grid gap-5 lg:grid-cols-[0.85fr_1.15fr]"><article className="rounded-3xl border border-slate-700 bg-slate-900/35 p-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-amber-200">LATEST EVIDENCE</p><h2 className="mt-2 text-2xl font-extrabold text-white">최근 검증의 기준</h2>{latest ? <><div className="mt-5 grid grid-cols-3 gap-3"><div className="rounded-xl bg-slate-950/45 p-3"><p className="text-[10px] text-slate-500">학습 일수</p><p className="mt-1 font-mono text-lg text-slate-100">{summary?.trainingDates?.length ?? 0}</p></div><div className="rounded-xl bg-slate-950/45 p-3"><p className="text-[10px] text-slate-500">독립 검증</p><p className="mt-1 font-mono text-lg text-slate-100">{summary?.validationDates?.length ?? 0}</p></div><div className="rounded-xl bg-slate-950/45 p-3"><p className="text-[10px] text-slate-500">대상 종목</p><p className="mt-1 font-mono text-lg text-slate-100">{summary?.symbolCount ?? 0}</p></div></div><p className="mt-5 text-sm leading-relaxed text-slate-400">각 조건식은 신호 발생 뒤 다음 1분 시가에 진입하고, 정해진 익절·손절·보유시간과 왕복 비용을 반영합니다. 같은 시간대의 종가를 진입 가격으로 쓰지 않아 미래 정보가 섞이지 않도록 했습니다.</p></> : <p className="mt-4 text-sm leading-relaxed text-slate-400">현재는 연구 구조만 준비되어 있습니다. 예시 성과나 가짜 통과 조건식은 표시하지 않습니다.</p>}<div className="mt-5 rounded-xl border border-amber-300/20 bg-amber-300/[0.06] p-4 text-xs leading-relaxed text-amber-50"><strong>해석 경계:</strong> 이 결과는 연구·검증용이며, 미래 수익이나 개인별 투자 결정을 보장하지 않습니다.</div></article>
      <article className="rounded-3xl border border-slate-700 bg-slate-900/35 p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-200">CUMULATIVE SURVIVORS</p><h2 className="mt-2 text-2xl font-extrabold text-white">반복 검증을 통과한 조건식</h2><p className="mt-2 text-sm leading-relaxed text-slate-400">단일 하루가 아닌, 여러 스윕에서 독립 검증을 통과한 조합을 우선합니다.</p></div><Clock3 className="text-violet-200" size={22}/></div>{cumulative.length ? <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead className="border-b border-slate-700 text-[10px] uppercase tracking-[0.12em] text-slate-500"><tr><th className="pb-3">조건식</th><th className="pb-3 text-right">통과 회수</th><th className="pb-3 text-right">검증 거래</th><th className="pb-3 text-right">평균 OOS</th><th className="pb-3 text-right">최악 낙폭</th></tr></thead><tbody>{cumulative.map((item, index) => <tr key={item.strategyFingerprint} className="border-b border-slate-800/80 text-sm"><td className="py-3"><div className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-teal-300/10 font-mono text-xs text-teal-200">{index + 1}</span><div><p className="font-semibold text-slate-100">{formula(item.representative.rootGenomeJson)}</p><p className="mt-0.5 font-mono text-[10px] text-slate-500">{item.strategyFingerprint.slice(0, 12)}</p></div></div></td><td className="py-3 text-right font-mono text-slate-200">{item.verifiedSweepCount}</td><td className="py-3 text-right font-mono text-slate-200">{item.totalValidationTrades.toLocaleString()}</td><td className="py-3 text-right font-mono text-teal-200">{percent(item.averageValidationReturnPercent)}</td><td className="py-3 text-right font-mono text-rose-200">{percent(item.worstValidationMaxDrawdownPercent)}</td></tr>)}</tbody></table></div> : <div className="mt-5 flex min-h-52 flex-col items-center justify-center rounded-2xl border border-dashed border-slate-700 px-6 text-center"><ShieldCheck className="mb-3 text-slate-600" size={26}/><p className="text-sm font-bold text-slate-300">아직 생존 조건식이 없습니다.</p><p className="mt-2 max-w-md text-xs leading-relaxed text-slate-500">좋아 보이는 조합이라도 독립 검증에서 재현되지 않으면 생존 목록에 올리지 않습니다. 이 공란은 데이터 부족 또는 엄격한 선별의 결과입니다.</p></div>}</article></section>
  </div></main>;
}
