import type {
  IndicatorDefinition,
  IndicatorCategory,
} from "./trading";

export const INDICATOR_CATALOG: IndicatorDefinition[] = [
  // === 추세 (Trend) ===
  {
    type: "ma_position",
    label: "이동평균배열",
    category: "trend",
    availability: "available",
    parameters: [
      {
        key: "periods",
        label: "이평선 기간",
        type: "select",
        default: "5,20,60",
        options: [
          { value: "5,20", label: "5·20일" },
          { value: "5,20,60", label: "5·20·60일" },
          { value: "20,60,120", label: "20·60·120일" },
          { value: "20,60,120,240", label: "20·60·120·240일" },
        ],
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 15,
  },
  {
    type: "macd_rising",
    label: "MACD 상승",
    category: "trend",
    availability: "available",
    parameters: [
      {
        key: "lookback",
        label: "룩백 봉수",
        type: "number",
        min: 2,
        max: 20,
        step: 1,
        default: 3,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 12,
  },
  {
    type: "macd_level",
    label: "MACD 레벨",
    category: "trend",
    availability: "available",
    parameters: [
      {
        key: "threshold",
        label: "임계값",
        type: "number",
        min: -100,
        max: 100,
        step: 0.01,
        default: 0,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },
  {
    type: "macd_histogram",
    label: "MACD 히스토그램",
    category: "trend",
    availability: "available",
    parameters: [
      {
        key: "fast",
        label: "단기EMA",
        type: "number",
        min: 5,
        max: 50,
        step: 1,
        default: 12,
      },
      {
        key: "slow",
        label: "장기EMA",
        type: "number",
        min: 10,
        max: 100,
        step: 1,
        default: 26,
      },
      {
        key: "signal",
        label: "시그널",
        type: "number",
        min: 3,
        max: 30,
        step: 1,
        default: 9,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },
  {
    type: "vwap",
    label: "VWAP",
    category: "trend",
    availability: "coming_soon",
    parameters: [
      {
        key: "period",
        label: "기간",
        type: "number",
        min: 1,
        max: 60,
        step: 1,
        default: 20,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 12,
  },
  {
    type: "disparity",
    label: "이격도",
    category: "trend",
    availability: "available",
    parameters: [
      {
        key: "period",
        label: "이평기간",
        type: "number",
        min: 5,
        max: 120,
        step: 1,
        default: 20,
      },
      {
        key: "threshold",
        label: "이격도(%)",
        type: "number",
        min: 80,
        max: 130,
        step: 0.5,
        default: 100,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },
  {
    type: "envelope",
    label: "엔벨로프",
    category: "trend",
    availability: "available",
    parameters: [
      {
        key: "period",
        label: "기간",
        type: "number",
        min: 5,
        max: 60,
        step: 1,
        default: 20,
      },
      {
        key: "percent",
        label: "폭(%)",
        type: "number",
        min: 1,
        max: 20,
        step: 0.5,
        default: 5,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },
  {
    type: "adx",
    label: "ADX",
    category: "trend",
    availability: "coming_soon",
    parameters: [
      {
        key: "period",
        label: "기간",
        type: "number",
        min: 7,
        max: 50,
        step: 1,
        default: 14,
      },
      {
        key: "threshold",
        label: "임계값",
        type: "number",
        min: 10,
        max: 80,
        step: 1,
        default: 25,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 12,
  },
  {
    type: "dmi",
    label: "DMI",
    category: "trend",
    availability: "coming_soon",
    parameters: [
      {
        key: "period",
        label: "기간",
        type: "number",
        min: 7,
        max: 50,
        step: 1,
        default: 14,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },

  // === 모멘텀 (Momentum) ===
  {
    type: "rsi",
    label: "RSI",
    category: "momentum",
    availability: "available",
    parameters: [
      {
        key: "period",
        label: "기간",
        type: "number",
        min: 2,
        max: 50,
        step: 1,
        default: 14,
      },
      {
        key: "threshold",
        label: "임계값",
        type: "number",
        min: 0,
        max: 100,
        step: 1,
        default: 70,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 12,
  },
  {
    type: "stochastic",
    label: "스토캐스틱",
    category: "momentum",
    availability: "available",
    parameters: [
      {
        key: "period",
        label: "기간",
        type: "number",
        min: 3,
        max: 50,
        step: 1,
        default: 14,
      },
      {
        key: "threshold",
        label: "임계값(%)",
        type: "number",
        min: 0,
        max: 100,
        step: 1,
        default: 80,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },
  {
    type: "williams_r",
    label: "Williams %R",
    category: "momentum",
    availability: "available",
    parameters: [
      {
        key: "period",
        label: "기간",
        type: "number",
        min: 5,
        max: 50,
        step: 1,
        default: 14,
      },
      {
        key: "threshold",
        label: "임계값",
        type: "number",
        min: -100,
        max: 0,
        step: 1,
        default: -20,
      },
    ],
    defaultComparator: "lte",
    defaultWeight: 10,
  },
  {
    type: "cci",
    label: "CCI",
    category: "momentum",
    availability: "available",
    parameters: [
      {
        key: "period",
        label: "기간",
        type: "number",
        min: 5,
        max: 60,
        step: 1,
        default: 20,
      },
      {
        key: "threshold",
        label: "임계값",
        type: "number",
        min: -300,
        max: 300,
        step: 10,
        default: 100,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },
  {
    type: "high_return",
    label: "고수익률",
    category: "momentum",
    availability: "available",
    parameters: [
      {
        key: "days",
        label: "기간(일)",
        type: "number",
        min: 1,
        max: 120,
        step: 1,
        default: 11,
      },
      {
        key: "minPercent",
        label: "최소(%)",
        type: "number",
        min: 1,
        max: 200,
        step: 1,
        default: 20,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 15,
  },
  {
    type: "close_change",
    label: "종가변동",
    category: "momentum",
    availability: "available",
    parameters: [
      {
        key: "days",
        label: "기간(일)",
        type: "number",
        min: 1,
        max: 60,
        step: 1,
        default: 1,
      },
      {
        key: "threshold",
        label: "임계값(%)",
        type: "number",
        min: -30,
        max: 30,
        step: 0.5,
        default: 2,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },
  {
    type: "new_high",
    label: "신고가",
    category: "momentum",
    availability: "available",
    parameters: [
      {
        key: "period",
        label: "기간(봉)",
        type: "number",
        min: 2,
        max: 240,
        step: 1,
        default: 5,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 12,
  },
  {
    type: "new_high_low",
    label: "신고가/신저가",
    category: "momentum",
    availability: "coming_soon",
    parameters: [
      {
        key: "period",
        label: "기간(봉)",
        type: "number",
        min: 2,
        max: 240,
        step: 1,
        default: 60,
      },
      {
        key: "mode",
        label: "모드",
        type: "select",
        default: "high",
        options: [
          { value: "high", label: "신고가" },
          { value: "low", label: "신저가" },
        ],
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 12,
  },

  // === 변동성 (Volatility) ===
  {
    type: "bollinger",
    label: "볼린저밴드",
    category: "volatility",
    availability: "available",
    parameters: [
      {
        key: "period",
        label: "기간",
        type: "number",
        min: 5,
        max: 60,
        step: 1,
        default: 20,
      },
      {
        key: "deviation",
        label: "표준편차",
        type: "number",
        min: 1,
        max: 4,
        step: 0.5,
        default: 2,
      },
      {
        key: "band",
        label: "밴드",
        type: "select",
        default: "upper",
        options: [
          { value: "upper", label: "상단" },
          { value: "middle", label: "중단" },
          { value: "lower", label: "하단" },
        ],
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 12,
  },
  {
    type: "atr_percent",
    label: "ATR%",
    category: "volatility",
    availability: "available",
    parameters: [
      {
        key: "period",
        label: "기간",
        type: "number",
        min: 5,
        max: 60,
        step: 1,
        default: 14,
      },
      {
        key: "threshold",
        label: "임계값(%)",
        type: "number",
        min: 0.5,
        max: 30,
        step: 0.5,
        default: 3,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },
  {
    type: "gap_percent",
    label: "갭%",
    category: "volatility",
    availability: "available",
    parameters: [
      {
        key: "threshold",
        label: "임계값(%)",
        type: "number",
        min: -10,
        max: 10,
        step: 0.5,
        default: 1,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },
  {
    type: "intrabar_position",
    label: "봉내위치",
    category: "volatility",
    availability: "available",
    parameters: [
      {
        key: "threshold",
        label: "위치(%)",
        type: "number",
        min: 0,
        max: 100,
        step: 5,
        default: 70,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 8,
  },
  {
    type: "price_range",
    label: "가격레인지",
    category: "volatility",
    availability: "available",
    parameters: [
      {
        key: "minPrice",
        label: "최소가격(원)",
        type: "number",
        min: 0,
        max: 1000000,
        step: 100,
        default: 1000,
      },
      {
        key: "maxPrice",
        label: "최대가격(원)",
        type: "number",
        min: 0,
        max: 10000000,
        step: 1000,
        default: 100000,
      },
    ],
    defaultComparator: "between",
    defaultWeight: 5,
  },

  // === 거래량 (Volume) ===
  {
    type: "turnover",
    label: "거래대금",
    category: "volume",
    availability: "available",
    parameters: [
      {
        key: "days",
        label: "기간(일)",
        type: "number",
        min: 1,
        max: 60,
        step: 1,
        default: 5,
      },
      {
        key: "threshold",
        label: "임계값(억원)",
        type: "number",
        min: 1,
        max: 5000,
        step: 10,
        default: 50,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 12,
  },
  {
    type: "volume_ratio",
    label: "거래량비율",
    category: "volume",
    availability: "available",
    parameters: [
      {
        key: "period",
        label: "기준기간(일)",
        type: "number",
        min: 3,
        max: 120,
        step: 1,
        default: 20,
      },
      {
        key: "threshold",
        label: "임계값(배)",
        type: "number",
        min: 0.1,
        max: 20,
        step: 0.1,
        default: 1.5,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 12,
  },
  {
    type: "turnover_count",
    label: "거래대금횟수",
    category: "volume",
    availability: "available",
    parameters: [
      {
        key: "days",
        label: "기간(일)",
        type: "number",
        min: 1,
        max: 60,
        step: 1,
        default: 5,
      },
      {
        key: "threshold",
        label: "기준대금(억원)",
        type: "number",
        min: 1,
        max: 5000,
        step: 10,
        default: 50,
      },
      {
        key: "count",
        label: "횟수",
        type: "number",
        min: 1,
        max: 30,
        step: 1,
        default: 3,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },
  {
    type: "volume_ratio_count",
    label: "거래량비율횟수",
    category: "volume",
    availability: "available",
    parameters: [
      {
        key: "days",
        label: "기간(일)",
        type: "number",
        min: 1,
        max: 60,
        step: 1,
        default: 5,
      },
      {
        key: "threshold",
        label: "기준배율",
        type: "number",
        min: 0.5,
        max: 10,
        step: 0.5,
        default: 2,
      },
      {
        key: "count",
        label: "횟수",
        type: "number",
        min: 1,
        max: 20,
        step: 1,
        default: 2,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },
  {
    type: "obv",
    label: "OBV",
    category: "volume",
    availability: "available",
    parameters: [
      {
        key: "period",
        label: "기간",
        type: "number",
        min: 5,
        max: 60,
        step: 1,
        default: 20,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },
  {
    type: "turnover_ma",
    label: "거래대금이평",
    category: "volume",
    availability: "available",
    parameters: [
      {
        key: "period",
        label: "이평기간",
        type: "number",
        min: 3,
        max: 60,
        step: 1,
        default: 20,
      },
      {
        key: "threshold",
        label: "임계값(배)",
        type: "number",
        min: 0.5,
        max: 10,
        step: 0.5,
        default: 1.5,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },
  {
    type: "volume_profile",
    label: "볼륨프로파일",
    category: "volume",
    availability: "coming_soon",
    parameters: [
      {
        key: "period",
        label: "기간(일)",
        type: "number",
        min: 5,
        max: 60,
        step: 1,
        default: 20,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 8,
  },

  // === 캔들패턴 (Candle Pattern) ===
  {
    type: "bullish_candle_count",
    label: "연속양봉",
    category: "candle_pattern",
    availability: "available",
    parameters: [
      {
        key: "days",
        label: "관찰기간(일)",
        type: "number",
        min: 2,
        max: 30,
        step: 1,
        default: 5,
      },
      {
        key: "count",
        label: "최소횟수",
        type: "number",
        min: 1,
        max: 20,
        step: 1,
        default: 3,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },
  {
    type: "bearish_candle_count",
    label: "연속음봉",
    category: "candle_pattern",
    availability: "available",
    parameters: [
      {
        key: "days",
        label: "관찰기간(일)",
        type: "number",
        min: 2,
        max: 30,
        step: 1,
        default: 5,
      },
      {
        key: "count",
        label: "최소횟수",
        type: "number",
        min: 1,
        max: 20,
        step: 1,
        default: 3,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },
  {
    type: "gap_up",
    label: "갭상승",
    category: "candle_pattern",
    availability: "available",
    parameters: [
      {
        key: "threshold",
        label: "최소갭(%)",
        type: "number",
        min: 0.5,
        max: 15,
        step: 0.5,
        default: 2,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 10,
  },
  {
    type: "gap_down",
    label: "갭하락",
    category: "candle_pattern",
    availability: "available",
    parameters: [
      {
        key: "threshold",
        label: "최소갭(%)",
        type: "number",
        min: 0.5,
        max: 15,
        step: 0.5,
        default: 2,
      },
    ],
    defaultComparator: "lte",
    defaultWeight: 10,
  },
  {
    type: "n_pattern",
    label: "N자형패턴",
    category: "candle_pattern",
    availability: "coming_soon",
    parameters: [
      {
        key: "period",
        label: "관찰기간(일)",
        type: "number",
        min: 5,
        max: 60,
        step: 1,
        default: 20,
      },
      {
        key: "minSwing",
        label: "최소진폭(%)",
        type: "number",
        min: 3,
        max: 30,
        step: 1,
        default: 10,
      },
    ],
    defaultComparator: "gte",
    defaultWeight: 12,
  },
];

/** 카테고리별 한국어 라벨 매핑 */
export const CATEGORY_LABELS: Record<IndicatorCategory, string> = {
  trend: "추세",
  momentum: "모멘텀",
  volatility: "변동성",
  volume: "거래량",
  candle_pattern: "캔들패턴",
};

/** availability가 "available"인 지표만 반환 */
export function getAvailableIndicators(): IndicatorDefinition[] {
  return INDICATOR_CATALOG.filter((i) => i.availability === "available");
}

/** 특정 카테고리에 속하는 지표 목록 반환 */
export function getIndicatorsByCategory(
  category: IndicatorCategory,
): IndicatorDefinition[] {
  return INDICATOR_CATALOG.filter((i) => i.category === category);
}
